### ISSUE TITLE
Create expense domain classes

### ISSUE THREAD

**Issue by ownerofglory** [ownerofglory/hillel-expense-tracker-backend#24]
Create classes that represent `expense` domain: 
`Expense` and `ExpenseDTO `
`ExpenseCategory` and  `ExpenseCategoryDTO`

Expense consists of
- amount
- description

ExpenseCategory consits of
- name

Relationships

`User` 1 -- * `Expense`
`ExpenseCategory` 1 -- * `Expense`

**!**
Depends on  [23](https://github.com/users/ownerofglory/projects/7?pane=issue&itemId=89914584&issue=ownerofglory%7Chillel-expense-tracker-backend%7C23)

**Comment by kate-livinska** [comment]
@ownerofglory - "Depends on https://github.com/users/ownerofglory/projects/7/views/1?pane=issue&itemId=89915387&issue=ownerofglory%7Chillel-expense-tracker-backend%7C24" - probably a typo here, as now this ticket depends on itself?

**Comment by ownerofglory** [comment]
@kate-livinska fixed. Thanks
