### ISSUE TITLE
Create mappers for domain objects

### ISSUE THREAD

**Issue by ownerofglory** [ownerofglory/hillel-expense-tracker-backend#25]
Create mapper classes for converting domain objects:
model -> DTO
DTO -> Model
Recomendation: use mapstruct approach and [MapStruct annotation processor](https://mapstruct.org/)

Create mappers for existing domain classes, e.g. UserMapper

module: common
package: ua.ithillel.expensetracker.mapper

**Comment by kate-livinska** [comment]
@ownerofglory Please check the [pull request](https://github.com/ownerofglory/hillel-expense-tracker-backend/pull/46)
Thank you.
