### ISSUE TITLE
Create test pipeline

### ISSUE THREAD

**Issue by ownerofglory** [ownerofglory/hillel-expense-tracker-backend#5]
Create Github Actions test pipeline
The pipeline should be run on each push and execute unit tests using mvn

**Comment by ownerofglory** [comment]
hello, @kate-livinska 
is there an open PR for this task yet? 
if yes please mention it, otherwise please consider changing the status of the issue 😉
thanks

**Comment by kate-livinska** [comment]
Sorry, moved it by mistake when looking from my phone!

**Comment by kate-livinska** [comment]
Done: https://github.com/ownerofglory/hillel-expense-tracker-backend/pull/20
