### ISSUE TITLE
Write cron expressions for expense report

### ISSUE THREAD

**Issue by ownerofglory** [ownerofglory/hillel-expense-tracker-backend#60]
Write a cron expressions that will be used for scheduling automated expense report generation.
Consider following report types:
- weekly: every Monday
- monthly: on the 1st of each month 
- yearly: on January the 1st of each year 

Cron expressions reference:
https://www.baeldung.com/cron-expressions

You can you cron generator:
https://crontab.cronhub.io/

**Comment by RomanOresh** [comment]
# Crone Expressions
- weekly:   0 0 * * Mon (At 12:00 AM, only on Monday)
- monthly: 0 0 1 * * (At 12:00 AM, on day 1 of the month)
- yearly: 0 0 0 1 1 * (At 12:00 AM, on day 1 of the month, only in January)

**Comment by ownerofglory** [comment]
@RomanOresh please document these expressions on project Wiki
https://github.com/ownerofglory/hillel-expense-tracker-backend/wiki
thanks!
